### ISSUE TITLE
Nothing provides libboost_locale.so.1.69.0

### ISSUE THREAD

**Issue by aabacchus** [MiKTeX/miktex-packaging#229] opened 2021-03-03 11:10 UTC
When performing an upgrade on Fedora 33, there is a newer version of MiKTeX (21.1); I have 20.12 installed.
However, dnf gives this error:

     Problem: cannot install the best update candidate for package miktex-20.12-1.fc32.x86_64
      - nothing provides libboost_locale.so.1.69.0()(64bit) needed by miktex-21.1-1.fc32.x86_64

Also, there is no MiKTeX repo for Fedora 33, which was released 4 months ago.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment] 2021-03-03 11:21
Duplicate of MiKTeX/miktex#698

**Closed by edocevoli** 2021-03-03 11:21 UTC
