### ISSUE TITLE
iftex.sty missing

### ISSUE THREAD

**Issue by JonDoyle** [MiKTeX/miktex-packaging#140] opened 2019-11-04 13:52 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

After updating my packages, it appears that the file iftex.sty loaded
by ifluatex.sty has disappeared.

In my installation files, iftex.sty does not appear under tex/generic/iftex, nor under tex/latex/iftex.

Every attempt to recompile my file, in which none of the packaging
information has changed, instigates an attempt to download the
package.  Across numerous attempts, the result is the same, no matter
what mirror is used.  The MiKTeX log file refers to some other program
having use of the file, but this happens even when compilation takes
place after rebooting my machine and with no prior invocations. 

My MWE, trial.tex attached, does nothing but load the package.

[trial.txt](https://github.com/MiKTeX/miktex-packaging/files/3804263/trial.txt)
[trial-initexmf.txt](https://github.com/MiKTeX/miktex-packaging/files/3804265/trial-initexmf.txt)
[trial-logwindow.txt](https://github.com/MiKTeX/miktex-packaging/files/3804266/trial-logwindow.txt)
[trial-report.txt](https://github.com/MiKTeX/miktex-packaging/files/3804267/trial-report.txt)

**Comment by edocevoli** [comment] 2019-11-04 14:14
Duplicate of #138

**Closed by edocevoli** 2019-11-04 14:14 UTC

**Comment by edocevoli** [comment] 2019-11-04 14:57
So the obvious workaround is: make sure that package `iftex` is installed.

**Comment by JonDoyle** [comment] 2019-11-11 13:00
The problem does not seem to be that the iftex package is not installed.
It was installed (and had been for years) at the time the error occurred,
and as my error report stated, when I checked the iftex directory,
iftex.sty was not in it (though some others were there).

Just to be sure, I ran the package installer via the MiKTeX console only to
discover it listed iftex as uninstalled. I (re)installed it, observed that
it put the missing files back in the iftex directory.  I then reran
pdflatex, but the error reoccurred, invoking the on-the-fly package
installer.  But when I check the iftex directory after this, only two of
the files placed there by the installer are still there, and iftex.sty is
one of the missing ones.

So something is going wrong somewhere.  I am only doing ordinary things,
with nothing changing in my installation (regularly updated).  Unless there
is some Windows 10 change that might be causing this.

Thank you for any help you can offer.

Jon Doyle


Contents of iftex directory after error:   ifetex.sty, ifluatex.sty

Error report during pdflatex (in an Emacs shell)

("C:\Program Files\MiKTeX2.9\tex/generic/iftex\ifluatex.sty"
======================================================================
starting package maintenance...
installation directory: "C:\Program Files\MiKTeX2.9"
package repository:
https://mirror.koddos.net/CTAN/systems/win32/miktex/tm/packages/
package repository digest: 760a08f296ffde4cc78f15181f77d735
going to download 240321 bytes
going to install 10 file(s) (1 package(s))
downloading
https://mirror.koddos.net/CTAN/systems/win32/miktex/tm/packages/iftex.tar.lzma.
..
0.24 MB, 2.12 Mbit/s
extracting files from iftex.tar.lzma...

Unfortunately, the package iftex could not be installed.
Please check the log file:
C:\Users\Doyle\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log
======================================================================


! LaTeX Error: File `iftex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Corresponding contents of
C:\Users\Doyle\AppData\Local\MiKTeX\2.9\miktex\log\pdflatex.log


2019-11-11 07:44:36,914-0500 INFO  pdflatex - starting with command line:
pdflatex interaction
2019-11-11 07:44:36,914-0500 INFO  pdflatex - allowing known shell commands
2019-11-11 07:44:36,914-0500 INFO  pdflatex - enabling input (output) from
(to) processes
2019-11-11 07:44:37,130-0500 INFO  pdflatex - installing package iftex
triggered by tex/latex/iftex\iftex.sty
2019-11-11 07:44:40,161-0500 INFO  pdflatex - mpm: starting package
maintenance...
2019-11-11 07:44:40,161-0500 INFO  pdflatex - mpm: installation directory:
"C:\Program Files\MiKTeX2.9"
2019-11-11 07:44:40,161-0500 INFO  pdflatex - mpm: package repository:
https://mirror.koddos.net/CTAN/systems/win32/miktex/tm/packages/
2019-11-11 07:44:40,339-0500 INFO  pdflatex - mpm: package repository
digest: 760a08f296ffde4cc78f15181f77d735
2019-11-11 07:44:41,188-0500 INFO  pdflatex - mpm: going to download 240321
bytes
2019-11-11 07:44:41,188-0500 INFO  pdflatex - mpm: going to install 10
file(s) (1 package(s))
2019-11-11 07:44:41,822-0500 INFO  pdflatex - mpm: downloading
https://mirror.koddos.net/CTAN/systems/win32/miktex/tm/packages/iftex.tar.lzma.
..
2019-11-11 07:44:42,721-0500 INFO  pdflatex - mpm: 0.24 MB, 2.12 Mbit/s
2019-11-11 07:44:42,759-0500 INFO  pdflatex - mpm: extracting files from
iftex.tar.lzma...
2019-11-11 07:44:42,806-0500 FATAL pdflatex - Windows API error 32: The
process cannot access the file because it is being used by another process.

2019-11-11 07:44:42,806-0500 FATAL pdflatex - Info: ="path="C:\Program
Files\MiKTeX2.9\tex\generic\iftex\ifluatex.sty""
2019-11-11 07:44:42,806-0500 FATAL pdflatex - Source:
Libraries\MiKTeX\Core\File\win\winFile.cpp
2019-11-11 07:44:42,806-0500 FATAL pdflatex - Line: 321
2019-11-11 07:44:53,922-0500 INFO  pdflatex - finishing with exit code 0

As in my original report, this happens even after a reboot with nothing but
Emacs running, so I have no idea what other process might be causing the
Windows API error.

**Comment by moewew** [comment] 2019-11-12 06:42
@JonDoyle Sometimes a simple update does not refresh the package database that is used for on-the-fly installation. This is especially true on an Admin-&-User system.

Just to be sure update MikTeX via the MikTeX Console in Admin mode *and* in User mode. Then open the Console in Admin mode and run *Tasks > Update package database*, repeat this step in User mode as well.

Cross your fingers and hope that this works. If it does not, remove `iftex` and all other older `if...tex` packages in both Admin and User mode (if installed) and re-install only `iftex` in *either* Admin *or* User mode (but *not* in both).

**Comment by JonDoyle** [comment] 2019-11-12 13:46
Thanks very much, I'll try this.

**Comment by JonDoyle** [comment] 2019-11-12 14:03
Yes, it worked!  Thank you very much again for the help.

Jon Doyle

**Comment by fahadijaz** [comment] 2021-02-08 23:29
Hi @JonDoyle,
Could you please outline the steps you performed that made it work?

**Comment by JonDoyle** [comment] 2021-02-09 16:55
It has been over a year since I had this trouble, so my memory might be
slightly off.  But as best I recall following the steps recommended by
moewew  as follows worked.

I run an Admin+User installation, and sometimes for that one apparently
needs to refresh the package database for both the Admin and the user
accounts.
1.  Open MikTeX console in Admin mode, then run Tasks > Update package
database.
2. Close the console and open it in User mode, then run Tasks > Update
package database.
*** I am not sure if doing these steps in this order worked.  Try the
reverse order if it does not.  If neither works, try doing it AUA, or UAU.
I'm pretty sure I did not need to run both modes twice.

Hope it works for you.

Jon Doyle

Moewew's suggestion:

@JonDoyle <https://github.com/JonDoyle> Sometimes a simple update does not
refresh the package database that is used for on-the-fly installation. This
is especially true on an Admin-&-User system.

Just to be sure update MikTeX via the MikTeX Console in Admin mode *and* in
User mode. Then open the Console in Admin mode and run *Tasks > Update
package database*, repeat this step in User mode as well.

Cross your fingers and hope that this works. If it does not, remove iftex
and all other older if...tex packages in both Admin and User mode (if
installed) and re-install only iftex in *either* Admin *or* User mode (but
*not* in both).
