### ISSUE TITLE
Need to reinstall miktex-console_admin

### ISSUE THREAD

**Issue by fbthl** [MiKTeX/miktex-packaging#435] opened 2024-05-19 16:41 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)
Since the last update of my miktex-installation on April 27. 2024, miktex console can not be started.
Once tried, there's an alert window with the text:
"This application failed to start becaus no Qt platform plugin coult be initialized. Reinstalling the application may fix this problem."
Is there a possibility to reinstall the console without reinstalling the complete MikTeX-installation?
Many thanks
Friedhart Belthle

**Comment by edocevoli** [comment] 2024-05-20 18:03
Duplicate of MiKTeX/miktex#1486

**Closed by edocevoli** 2024-05-20 18:03 UTC
