### ISSUE TITLE
MikTeX has not been updated since September 6th.

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex-packaging#194] opened 2020-10-03 09:00 UTC
Sorry to ask this question here, but I'm wondering about the lack of updates in MikTeX, especially since [TikZ pgf](https://www.ctan.org/pkg/pgf) has just been updated to version 3.1.6a. 

When do you plan to update MikTeX?

**Comment by edocevoli** [comment] 2020-10-03 12:49
Duplicate of #191

**Closed by edocevoli** 2020-10-03 12:49 UTC
