### ISSUE TITLE
LaTeX Error: File `ifpdf.sty' not found.

### ISSUE THREAD

**Issue by Cash4Programming** [MiKTeX/miktex-packaging#143] opened 2019-11-16 04:16 UTC
I compiled my Latex document.  

I then update all available miktex packages and once I did that I could no longer compile anything

[Math 085 Ch 4_Answers.log](https://github.com/MiKTeX/miktex-packaging/files/3853807/Math.085.Ch.4_Answers.log)

My latex document is:

\documentclass[a4paper,12pt]{article}      % type of latex document
\usepackage{pdfsync}                       % SumatraPDF synchronization
\usepackage{etoolbox}                      % for boolean flags
    \newbool{isTest}                       % true  - test for students
    \setbool{isTest}{false}                % false - answer key

\usepackage{xcolor}             % Allows text and page background colors to be set.

\ifbool{isTest}{
  \newcommand{\BLACK}{black}
  \newcommand{\RED}{red}
  \newcommand{\BLUE}{blue}
  \newcommand{\GREEN}{coolgrey}
  \newcommand{\CYAN}{cadetgrey} 
  \newcommand{\EONE}{charcoal} %magenta}
  \newcommand{\ETWO}{darkgray} %cyan}
  \newcommand{\EQN}{cadet}
  \newcommand{\PURPLE}{charcoal}
	\newcommand{\WHITE}{white}  
  \newcommand{\ORANGE}{dimgray}
  \newcommand{\YELLOW}{darkgray}
  \newcommand{\LIGHTVIOLET}{feldgrau}
  \newcommand{\ROYALBLUE}{gray}
  \newcommand{\SLATEBLUE}{darkslategray}
	
	%
	% http://latexcolor.com/
	%
	% for black
	\definecolor{outerspace}{rgb}{0.25, 0.29, 0.3}
	% Shade of grey
	\definecolor{aurometalsaurus}{rgb}{0.43, 0.5, 0.5}
	\definecolor{battleshipgrey}{rgb}{0.52, 0.52, 0.51}
	\definecolor{cadet}{rgb}{0.33, 0.41, 0.47}
	\definecolor{cadetgrey}{rgb}{0.57, 0.64, 0.69}
	\definecolor{ashgrey}{rgb}{0.7, 0.75, 0.71}
	\definecolor{charcoal}{rgb}{0.21, 0.27, 0.31}
	\definecolor{coolgrey}{rgb}{0.55, 0.57, 0.67}
	\definecolor{copperrose}{rgb}{0.6, 0.4, 0.4}
	\definecolor{darkgray}{rgb}{0.66, 0.66, 0.66}
	\definecolor{darkslategray}{rgb}{0.18, 0.31, 0.31}
	\definecolor{davysgrey}{rgb}{0.33, 0.33, 0.33}
	\definecolor{dimgray}{rgb}{0.41, 0.41, 0.41}
	\definecolor{feldgrau}{rgb}{0.3, 0.36, 0.33}
	\definecolor{gray}{rgb}{0.5, 0.5, 0.5}
	\definecolor{silver}{rgb}{0.75, 0.75, 0.75}
	\definecolor{gray-asparagus}{rgb}{0.27, 0.35, 0.27}
	\definecolor{grullo}{rgb}{0.66, 0.6, 0.53}
	\definecolor{lightgray}{rgb}{0.83, 0.83, 0.83}
	\definecolor{lightslategray}{rgb}{0.47, 0.53, 0.6}
	\definecolor{liver}{rgb}{0.33, 0.29, 0.31}
	\definecolor{manatee}{rgb}{0.59, 0.6, 0.67}
	\definecolor{palesilver}{rgb}{0.79, 0.75, 0.73}
	\definecolor{pastelgray}{rgb}{0.81, 0.81, 0.77}
	\definecolor{paynesgrey}{rgb}{0.25, 0.25, 0.28}
	\definecolor{slategray}{rgb}{0.44, 0.5, 0.56}
	\definecolor{taupegray}{rgb}{0.55, 0.52, 0.54}
	\definecolor{trolleygrey}{rgb}{0.5, 0.5, 0.5}
}{
  \newcommand{\BLACK}{black}
  \newcommand{\RED}{red}
  \newcommand{\BLUE}{blue}
  \newcommand{\GREEN}{green}
  \newcommand{\CYAN}{cyan}
  \newcommand{\EONE}{magenta}
  \newcommand{\ETWO}{cyan}
  \newcommand{\EQN}{magenta!50!cyan}
  \newcommand{\PURPLE}{purple}
  \newcommand{\WHITE}{white}  
  \newcommand{\ORANGE}{orange}
  \newcommand{\YELLOW}{yellow}
  \newcommand{\LIGHTVIOLET}{LightViolet}
  \newcommand{\ROYALBLUE}{RoyalBlue}
  \newcommand{\SLATEBLUE}{SlateBlue}
	
  \definecolor{\YELLOW}{rgb}{1.0, 1.0, 0.0}
	\definecolor{\ROYALBLUE}{RGB}{65,105,225}
  \definecolor{\SLATEBLUE}{RGB}{106,90,205}
  \definecolor{\LIGHTVIOLET}{RGB}{205,91,205}

	%
	% http://latexcolor.com/
	%
	% for black
	\definecolor{outerspace}{rgb}{0.25, 0.29, 0.3}
	% Shade of grey
	\definecolor{aurometalsaurus}{rgb}{0.43, 0.5, 0.5}
	\definecolor{battleshipgrey}{rgb}{0.52, 0.52, 0.51}
	\definecolor{cadet}{rgb}{0.33, 0.41, 0.47}
	\definecolor{cadetgrey}{rgb}{0.57, 0.64, 0.69}
	\definecolor{ashgrey}{rgb}{0.7, 0.75, 0.71}
	\definecolor{charcoal}{rgb}{0.21, 0.27, 0.31}
	\definecolor{coolgrey}{rgb}{0.55, 0.57, 0.67}
	\definecolor{copperrose}{rgb}{0.6, 0.4, 0.4}
	\definecolor{darkgray}{rgb}{0.66, 0.66, 0.66}
	\definecolor{darkslategray}{rgb}{0.18, 0.31, 0.31}
	\definecolor{davysgrey}{rgb}{0.33, 0.33, 0.33}
	\definecolor{dimgray}{rgb}{0.41, 0.41, 0.41}
	\definecolor{feldgrau}{rgb}{0.3, 0.36, 0.33}
	\definecolor{gray}{rgb}{0.5, 0.5, 0.5}
	\definecolor{silver}{rgb}{0.75, 0.75, 0.75}
	\definecolor{gray-asparagus}{rgb}{0.27, 0.35, 0.27}
	\definecolor{grullo}{rgb}{0.66, 0.6, 0.53}
	\definecolor{lightgray}{rgb}{0.83, 0.83, 0.83}
	\definecolor{lightslategray}{rgb}{0.47, 0.53, 0.6}
	\definecolor{liver}{rgb}{0.33, 0.29, 0.31}
	\definecolor{manatee}{rgb}{0.59, 0.6, 0.67}
	\definecolor{palesilver}{rgb}{0.79, 0.75, 0.73}
	\definecolor{pastelgray}{rgb}{0.81, 0.81, 0.77}
	\definecolor{paynesgrey}{rgb}{0.25, 0.25, 0.28}
	\definecolor{slategray}{rgb}{0.44, 0.5, 0.56}
	\definecolor{taupegray}{rgb}{0.55, 0.52, 0.54}
	\definecolor{trolleygrey}{rgb}{0.5, 0.5, 0.5}
}
\usepackage[margin=1in]{geometry}
\usepackage[USenglish]{babel}  % Set language as US English %francais, polish, spanish, ...
\usepackage[T1]{fontenc}       % select new font encodings for output, that is, what fonts to use for printing characters
\usepackage[utf8]{inputenc}    % allows the user to input accented characters directly from the keyboard
\usepackage{fp}                % Simple addition and subtraction within latex
\let\FPADD\fpAdd               % redefine add and subtraction as it conflicts with multido package
\let\FPSUB\fbSub

**Comment by edocevoli** [comment] 2019-11-16 08:55
Duplicate of #141

**Closed** 2019-11-16 08:55 UTC
Labels: duplicate
