### ISSUE TITLE
Portable Edition does not work on Networkdrive

### ISSUE THREAD

**Issue by PrometeuszJasinski** [MiKTeX/miktex-packaging#429] opened 2024-04-15 06:41 UTC
Hi,

First of all, big thx for maintinging this great package.

I installed the package as portable on my local drive (Windows 10 Pro build 19045). (Remark: installing into OneDrive seems to be buggy, too). On the local drive it is working fine, but when I move it to our network folder (also NTFS), I cannot execute several .exe anymore. They all fail with the following issue:

pdflatex: Windows API error 995: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.
pdflatex: Data: path="W:\Tps_prj\DataSheets_Specs\MikTex_15_04_2024\texmfs/config\miktex/data/le\"

Entschuldigung, aber W:\Tps_prj\DataSheets_Specs\MikTex_15_04_2024\texmfs\install\miktex\bin\x64\pdflatex.exe schlug fehl.
ERROR: Der E/A-Vorgang wurde wegen eines Threadendes oder einer Anwendungsanforderung abgebrochen.

ERROR: Function: ReadDirectoryChangesW
ERROR: Result: 995
ERROR: Data: path="W:\Tps_prj\DataSheets_Specs\MikTex_15_04_2024\texmfs/config\miktex/data/le\"
ERROR: Source: Libraries\MiKTeX\Core\FileSystemWatcher\win\winFileSystemWatcher.cpp:150

I also tried installing as admin, but this is already not supported by the installer.

Also running miktex-portable.cmd ends with same 995 errors. 

This issue is also present with miktex 23.1. The version from 2018 was working fine in this constellation.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by edocevoli** [comment] 2024-04-18 14:37
Duplicate of #423

**Closed by edocevoli** 2024-04-18 14:37 UTC
