### ISSUE TITLE
kvoptions.sty missing

### ISSUE THREAD

**Issue by petKitsune** [MiKTeX/miktex-packaging#147] opened 2019-12-01 19:14 UTC
for the one who got this problem

after update MiKTeX today 19.12.01
i got an error on hyperref
File `kvoptions.sty' not found.
was working perfectly before the update

to solve this 
downloaded kvoptions.tds.zip from ctan
put the folders in the right place in your MiKTeX distro
refresh the file database
and its up and running again 

win10x64
MiKTeXx64 portable

**Comment by edocevoli** [comment] 2019-12-01 20:33
Duplicate of #145

**Closed by edocevoli** 2019-12-01 20:33 UTC

**Comment by petKitsune** [comment] 2019-12-01 21:16
somehow I missed that one
I need more coffee
