### ISSUE TITLE
kvoption module in oberdiek package error

### ISSUE THREAD

**Issue by nttphuc** [MiKTeX/miktex-packaging#145] opened 2019-12-01 12:31 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

The oberdiek package date 1/Dec/2019 seems to have a bug in kvoption module which cause error when compile with packages such as epstopdf and hyperef.

The error message is:
"File `kvoptions.sty' not found. \RequirePackage{kvoptions}[2007/10/02]"

**Comment by moewew** [comment] 2019-12-01 13:04
`kvoptions` was split from `oberdiek` into a stand-alone package (https://lists.dante.de/pipermail/ctan-ann/2019-December/013221.html). In tonight's MikTeX updates `oberdiek` was updated (and thus doesn't contain `kvoptions` any more, see https://miktex.org/Package/Browse/oberdiek), but `kvoptions` was not added to the package list (https://miktex.org/packages/kvoptions). (This is the same effect as https://tex.stackexchange.com/q/518757/35864).

`kvoptions` is used in some major LaTeX packages (most notably `hyperref` and other `oberdiek` packages, `mdframe`, `minted`, `biblatex`), so many documents, even very simple ones like this
```latex
\documentclass{article}
\usepackage{hyperref}

\begin{document}
Lorem
\end{document}
```
will fail now.

**Comment by u-fischer** [comment] 2019-12-01 13:09
As a work-around until miktex installs the package:

There is a tds.zip on ctan: http://mirrors.ctan.org/install/macros/latex/contrib/kvoptions.tds.zip

Unpack it somewhere outside miktex and then add the root folder (the one which contains the folder "tex") as a new root in miktex console -> settings -> directories.

**Comment by edocevoli** [comment] 2019-12-01 15:27
Yes, yesterday they removed `kvoptions` from `oberdiek`. The new `kvoptions` package was added today. Don't know who is to blame for the bad timing.

Will be fixed with the next update.

**Closed by edocevoli** 2019-12-01 15:27 UTC

**Comment by davidcarlisle** [comment] 2019-12-01 15:59
@edocevoli  yes sorry about that, I think it is hard to handle package moves at the ctan end, I made 8 separate uploads (7 split off bits plus a reduced oberdiek, marked as 1 of 8, 2 of 8 etc)  but I think the ctan volunteers can't really stage this, they handle them one at a time, updating the catalog live as each package is handled.

kvoptions (and stringenc) then had a query over tds locations (I had left "oberdiek" in one place in the build script for the final zip so those two packages were held back but the rest of the update  went live, and it was the next morning before I saw the email from ctan querying the build and I could fix it and re-submit.

So ultimately human error on my part was the cause although the distributed and volunteer process of getting files from here to the end user does leave several points of failure.

Improved testing so that particular error shouldn't happen again, but hard to catch everything....
