### ISSUE TITLE
GPG key expired

### ISSUE THREAD

**Issue by YitianXiao** [MiKTeX/miktex-packaging#244] opened 2021-05-17 09:48 UTC
- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

I'm using Miktex for Ubuntu and it seems the GPG key has expired.

pub   rsa2048 2017-06-23 [SC] [expired: 2021-04-27]
      D6BC 2435 65B2 087B C3F8  97C9 277A 7293 F59E 4889
uid           [ expired] MiKTeX Packager <packager@miktex.org>

W: GPG error: https://mirrors.dgut.edu.cn/CTAN/systems/win32/miktex/setup/deb focal InRelease: The following signatures were invalid: EXPKEYSIG 277A7293F59E4889 MiKTeX Packager <packager@miktex.org>

**Comment by edocevoli** [comment] 2021-05-17 13:50
Duplicate of #241

**Closed by edocevoli** 2021-05-17 13:50 UTC
