### ISSUE TITLE
Is there a bug with the `lipsum` package in the last update of MikTeX?

### ISSUE THREAD

**Issue by AndreC75** [MiKTeX/miktex-packaging#68] opened 2018-11-24 08:13 UTC
I have the full version of MikTeX updated today. When testing the code on page 396 of the following tcolorbox manual 4.14, it is requested to install the lipsum package which is normally included in MikTeX. I installed it, but the compilation still fails.
https://tex.stackexchange.com/q/461526/138900

**Comment by edocevoli** [comment] 2018-11-24 10:43
Duplicate of #67

**Closed by edocevoli** 2018-11-24 10:43 UTC
