### ISSUE TITLE
Cannot download MikTeX net-installer from website.

### ISSUE THREAD

**Issue by gabcavic** [MiKTeX/miktex-packaging#300] opened 2022-10-21 07:45 UTC
Hi to everyone,
I'm writing this issue to notify that the net-installer for Windows 64-bit is not available on MikTeX site. The page which should contain the installer shows a 404 not found error (https://miktex.org/download/ctan/systems/win32/miktex/setup/windows-x64/setup-5.3.1+b8f430f-x64.exe), here below you also find a screen of the problem.
The same problem appears when downloading the MikTeX setup utility for 64-bit windows system, while no problems for the basic installer

![image](https://user-images.githubusercontent.com/38323760/197141248-43280017-1784-4431-85f2-8773cbb23269.png)

I hope this is the correct channel to post this issue. Otherwise I will file a new one on the channel you will point to me.

- [x] I have read the [MiKTeX Contributing Guidelines](https://github.com/MiKTeX/miktex-packaging/blob/master/CONTRIBUTING.md)

**Comment by gabcavic** [comment] 2022-10-21 07:50
I noticed there is already another issu dealing with the same problem in the main miktek repository. I link it here

https://github.com/MiKTeX/miktex/issues/1203

**Comment by edocevoli** [comment] 2022-10-21 10:26
This is a duplicate of https://github.com/MiKTeX/miktex/issues/1203

**Closed by edocevoli** 2022-10-21 10:26 UTC
