### ISSUE TITLE
Error when using pgf/tikz

### ISSUE THREAD

**Issue by LukasMD** [MiKTeX/miktex-packaging#81] opened 2019-01-07 13:27 UTC
Hi, it seems like the miktex package pgf is broken, it doesn't contain any files.

Just the simple \usepackage{tikz} command causes a "File 'tikz.sty' not found" error.

**Comment by AlanGillespie** [comment] 2019-01-07 13:38
The absence of 'pgfcore.sty' also breaks beamer

**Comment by LukasMD** [comment] 2019-01-07 13:42
just saw, that this issue has already been taken care of https://github.com/MiKTeX/miktex-packaging/issues/80

**Comment by edocevoli** [comment] 2019-01-07 14:09
Duplicate of #80

**Closed by edocevoli** 2019-01-07 14:09 UTC
